# Generated by Django 3.2.3 on 2021-06-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('total', models.PositiveIntegerField(default=0)),
                ('paper', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
