# Generated by Django 3.2.3 on 2021-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='metal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='plastic',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
