# Generated by Django 3.2.3 on 2021-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210608_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='area',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='metal',
            new_name='Battery',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='paper',
            new_name='CommunicatioMaterial',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='plastic',
            new_name='EdibleOil',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='total',
            new_name='ElectricaEquipment',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='year',
            new_name='Year',
        ),
        migrations.AddField(
            model_name='type',
            name='EnvironmentalAgentsContainers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Glass',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Metal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Others',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Paper',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Plastic',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Textile',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='Total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
