# Generated by Django 3.2.3 on 2021-06-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20210609_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='Others',
            new_name='其他',
        ),
    ]
