# Generated by Django 3.2.3 on 2021-06-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_rename_others_type_其他'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='Area',
            new_name='地區',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Battery',
            new_name='塑膠橡膠',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='CommunicatioMaterial',
            new_name='家用電品',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Year',
            new_name='年度',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='EdibleOil',
            new_name='特殊用藥廢容器',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='ElectricaEquipment',
            new_name='玻璃',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='EnvironmentalAgentsContainers',
            new_name='紙類',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Glass',
            new_name='紡織品',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Metal',
            new_name='總計',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Paper',
            new_name='通訊物品',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Plastic',
            new_name='金屬類',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Textile',
            new_name='電池',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='Total',
            new_name='食用油',
        ),
    ]
