# Generated by Django 3.1.7 on 2021-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210609_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('地區', models.CharField(max_length=200)),
                ('民國100年', models.PositiveIntegerField(default=0)),
                ('民國101年', models.PositiveIntegerField(default=0)),
                ('民國102年', models.PositiveIntegerField(default=0)),
                ('民國103年', models.PositiveIntegerField(default=0)),
                ('民國104年', models.PositiveIntegerField(default=0)),
                ('民國105年', models.PositiveIntegerField(default=0)),
                ('民國106年', models.PositiveIntegerField(default=0)),
                ('民國107年', models.PositiveIntegerField(default=0)),
                ('民國108年', models.PositiveIntegerField(default=0)),
                ('民國109年', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
