# Generated by Django 3.2.3 on 2021-06-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20210620_2248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M',
        ),
    ]
