# Generated by Django 3.2.3 on 2021-06-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_other'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paper1',
            new_name='Metal',
        ),
    ]
