# Generated by Django 3.2.3 on 2021-06-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_rename_paper1_metal'),
    ]

    operations = [
        migrations.CreateModel(
            name='宜蘭縣',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('年度', models.CharField(max_length=200)),
                ('民國100年', models.PositiveIntegerField(default=0)),
                ('民國101年', models.PositiveIntegerField(default=0)),
                ('民國102年', models.PositiveIntegerField(default=0)),
                ('民國103年', models.PositiveIntegerField(default=0)),
                ('民國104年', models.PositiveIntegerField(default=0)),
                ('民國105年', models.PositiveIntegerField(default=0)),
                ('民國106年', models.PositiveIntegerField(default=0)),
                ('民國107年', models.PositiveIntegerField(default=0)),
                ('民國108年', models.PositiveIntegerField(default=0)),
                ('民國109年', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
