# Generated by Django 3.2.3 on 2021-06-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_宜蘭縣'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='宜蘭縣',
            new_name='Yilan',
        ),
    ]
