# Generated by Django 3.2.3 on 2021-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_rename_宜蘭縣_yilan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yilan',
            old_name='民國100年',
            new_name='其他',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國101年',
            new_name='塑膠橡膠',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國102年',
            new_name='家用電品',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國103年',
            new_name='特殊用藥廢容器',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國104年',
            new_name='玻璃',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國105年',
            new_name='紙類',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國106年',
            new_name='紡織品',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國107年',
            new_name='總計',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國108年',
            new_name='通訊物品',
        ),
        migrations.RenameField(
            model_name='yilan',
            old_name='民國109年',
            new_name='金屬類',
        ),
        migrations.AddField(
            model_name='yilan',
            name='電池',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yilan',
            name='食用油',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
