# Generated by Django 3.2.3 on 2021-06-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20210621_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keelung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('年度', models.CharField(max_length=200)),
                ('總計', models.PositiveIntegerField(default=0)),
                ('紙類', models.PositiveIntegerField(default=0)),
                ('金屬類', models.PositiveIntegerField(default=0)),
                ('塑膠橡膠', models.PositiveIntegerField(default=0)),
                ('玻璃', models.PositiveIntegerField(default=0)),
                ('紡織品', models.PositiveIntegerField(default=0)),
                ('家用電品', models.PositiveIntegerField(default=0)),
                ('電池', models.PositiveIntegerField(default=0)),
                ('通訊物品', models.PositiveIntegerField(default=0)),
                ('特殊用藥廢容器', models.PositiveIntegerField(default=0)),
                ('食用油', models.PositiveIntegerField(default=0)),
                ('其他', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
